version: '3'

services:
  telegram:
    build: ./telegram
    env_file:
      - ./env/telegram.env
      - ./env/dc.env
    restart:
      always

  nginx:
    build: ./nginx
    ports:
      - "${OUTER_PORT}:${NGINX_PORT}"
    env_file:
      - ./env/dc.env
    volumes:
      - /root/ssl_certs/conf:/etc/letsencrypt
      - /root/ssl_certs/www:/var/www/certbot
    restart:
      always
